src/Webapi/Dom/Webapi__Dom__Window.re

Relevant specification: https://www.w3.org/TR/selection-api/#webidl-1016100280
window.getSelection might return null it does so on Firefox if you try to get the selection object out of an iframe that is hidden inside a display: none block.

switched Window.getSelection to return an option since that call might return null

---

CHANGELOG.md
examples/webapi_example.res
lib/js/examples/webapi_example.js
src/Webapi.res
src/Webapi/Webapi__WebSocket.res
src/Webapi/Webapi__WebSocket.resi

Fixes #4 
Should cover most of the basics, and even a few of the details:
- Creating a WebSocket determines the type of binary messages that are received (blob or array buffer)
- Individual `send` bindings for each type of data supported

Add bindings for WebSocket

---

CHANGELOG.md
lib/js/tests/Webapi/Dom/Webapi__Dom__Document__test.js
lib/js/tests/Webapi/Dom/Webapi__Dom__HtmlDocument__test.js
src/Webapi/Dom/Webapi__Dom__Document.res
src/Webapi/Dom/Webapi__Dom__HtmlDocument.res
tests/Webapi/Dom/Webapi__Dom__Document__test.res
tests/Webapi/Dom/Webapi__Dom__HtmlDocument__test.res

Depends on #40 because it's going to cause conflicts and I don't want to wait until that merges to open this PR. I'll change the target branch here after it merges.
These are the primary remaining methods from our internal 'bs-webapi contrib' layer. There are still a few added modules I haven't ported but we can deal with those later (after 1.0 if I don't get time sooner).
With this, we should be able to switch to `include Webapi.Dom` instead of importing every module individually.
* ~Added `setActiveElement` to Document~ this was incorrect
* Moved `hasFocus` and `activeElement` from HtmlDocument to Document

Add missing APIs

---

.editorconfig
CHANGELOG.md
lib/js/tests/Webapi/Dom/Webapi__Dom__MutationObserver__test.js
src/Webapi/Dom/Webapi__Dom__MutationRecord.res
tests/Webapi/Dom/Webapi__Dom__MutationObserver__test.res

There was actually a lot more wrong than #54 suggested, looking at the spec! I also added a test.
* Corrected nullable return in `MutationRecord`
* Corrected spelling of `nextSibling`
Fixes #54

Corrected MutationRecord API

---

src/Webapi/Webapi__Fetch.res
src/Webapi/Webapi__Fetch.resi

Add response constructors

---

src/Webapi/Webapi__Fetch.res
src/Webapi/Webapi__Fetch.resi

Relates to #30 
As far as I can see this property does not exist in the spec, I assume it was superseded by `destination` but I don't have the context to know for sure.

Remove Request requestType

---

CHANGELOG.md
lib/js/tests/Webapi/Dom/Webapi__Dom__HtmlInputElement__test.js
src/Webapi/Dom/Webapi__Dom__Element.res
src/Webapi/Dom/Webapi__Dom__HtmlElement.res
tests/Webapi/Dom/Webapi__Dom__HtmlInputElement__test.res

Fixes #60
The main fix is using `Obj.magic` to correct the input type for the `ofElement` function, but I also took the opportunity to shorten `asHtmlElement`.
This implementation uses techniques [similar to what we do in TinyMCE](https://github.com/tinymce/tinymce/blob/715f59c3a8b2bb35d2a158902a1b245987185b17/modules/sand/src/main/ts/ephox/sand/api/SandHTMLElement.ts#L23) combined with [an unsubmitted patch I made](https://github.com/tinymce/tinymce/blob/eefccb613d7fd53cf7fe2f2c8b934be3f384b1be/modules/sand/src/main/ts/ephox/sand/api/SandHTMLElement.ts#L4) that is shorter but doesn't support IE11.

Fix `ofElement`

---

CHANGELOG.md
lib/js/tests/Webapi/Dom/Webapi__Dom__HtmlFormElement__test.js
src/Webapi/Dom/Webapi__Dom__Document.res
src/Webapi/Dom/Webapi__Dom__HtmlButtonElement.res
src/Webapi/Dom/Webapi__Dom__HtmlCollection.res
src/Webapi/Dom/Webapi__Dom__HtmlFieldSetElement.res
src/Webapi/Dom/Webapi__Dom__HtmlFormControlsCollection.res
src/Webapi/Dom/Webapi__Dom__HtmlFormControlsCollection.resi
src/Webapi/Dom/Webapi__Dom__HtmlFormElement.res
src/Webapi/Dom/Webapi__Dom__HtmlObjectElement.res
src/Webapi/Dom/Webapi__Dom__HtmlOptGroupElement.res
src/Webapi/Dom/Webapi__Dom__HtmlOptionElement.res
src/Webapi/Dom/Webapi__Dom__HtmlOptionsCollection.res
src/Webapi/Dom/Webapi__Dom__HtmlOutputElement.res
src/Webapi/Dom/Webapi__Dom__HtmlSelectElement.res
src/Webapi/Dom/Webapi__Dom__HtmlTextAreaElement.res
src/Webapi/Dom/Webapi__Dom__RadioNodeList.res
src/Webapi/Webapi__Dom.res
tests/Webapi/Dom/Webapi__Dom__HtmlFormElement__test.res

feat: HtmlFormControlsCollection and related elements

---

CHANGELOG.md
lib/js/tests/Webapi/Dom/Webapi__Dom__History__test.js
src/Webapi/Dom/Webapi__Dom__History.res
src/Webapi/Dom/Webapi__Dom__PopStateEvent.res
tests/Webapi/Dom/Webapi__Dom__History__test.res

Fixes #86.
Added tests for get as well as set scroll restoration.
Tweaked some types and documentation to make it more obvious how to use the state API.

Swap history scroll restoration to use 'auto' and 'manual'.

---

CHANGELOG.md
examples/dom_example.res
lib/js/tests/Webapi/Dom/Webapi__Dom__Node__test.js
src/Webapi/Dom/Webapi__Dom__Node.res
tests/Webapi/Dom/Webapi__Dom__HtmlFormElement__test.res
tests/Webapi/Dom/Webapi__Dom__Node__test.res
tests/Webapi/Webapi__IntersectionObserver__test.res

* Add `Node.insertAtEnd` binding
* Deprecate `Node.isSameNode`
Fixes #49
I'm not sure if more are required, I think these are the only ones that tripped us up when we migrated last year. We should verify this before merging.
I didn't change `isEqualNode` because the order doesn't matter.

Add named arguments to various `Node` apis

---

src/Webapi/Dom/Webapi__Dom__RectList.res
src/Webapi/Fetch/Webapi__Fetch__AbortController.res
src/Webapi/Webapi__FileList.res
src/Webapi/Webapi__Navigator.res
src/Webapi/Webapi__WorkerNavigator.res
tests/Webapi/Webapi__Navigator__test.res
tests/Webapi/Webapi__WorkerGlobalScope__test.res

As discussed with @illusionalsagacity, who contributed the types in #57, this makes `navigator` significantly easier to use.
The tests prove there is no change to the generated JS as a result of this.

Convert Navigator types to records

---

CHANGELOG.md
src/Webapi/Webapi__Url.res

The function 'URL.createObjectURL' can take File, Blob and MediaSource.  This PR simply adds a binding for Blob.

Add binding of createObjectURL that takes a Blob.

---

src/Webapi/Dom/Webapi__Dom__BeforeUnloadEvent.res

`returnValue` is writable : https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent

Add Webapi.Dom.BeforeUnloadEvent.returnValue setter

---

src/Webapi/Dom/Webapi__Dom__CssStyleDeclaration.res

I'm not certain this is right, as I'm not as familiar with the current incarnation of Rescripts externals.
My read of this code is that `setProperty` is intended to call
[setProperty](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty) with 2 arguments, and `setPropertyValue` is supposed to call `setProperty` with 3 arguments.
There are related functions `getProperty` and `getPropertyValue`, but there isn't a `setPropertyValue`, so my guess is there was a typo here.

Use correct name for setProperty

---

src/Webapi/Webapi__Url.res

This PR fixes the binding of URL.toJSON
https://developer.mozilla.org/en-US/docs/Web/API/URL/toJSON

fix URL.toJSON binding

---

CHANGELOG.md
src/Webapi/Dom/Webapi__Dom__CustomEvent.res

As seen in [1], the options is an object with a `detail` property, not the detail directly.
[1]: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

Fix the CustomEvent's makeWithOption signature.

---

lib/js/examples/fetch_examples.js
src/Webapi/Webapi__Fetch.res
src/Webapi/Webapi__Fetch.resi

Some small changes to get this package to compile with ReScript 11 in uncurried mode.

Fix compatibility with ReScript 11 uncurried mode

---

CHANGELOG.md
src/Webapi/Webapi__Blob.res
src/Webapi/Webapi__Fetch.res
src/Webapi/Webapi__File.res

Hello, thanks for this package :)
Using `@as` directive as no impact for rescript v9 or v10 but it works in rescript v11
with rescript v9
With rescript v10
With rescript v11
fix #128

fix method parameter for requestInit with rescript v11

---

CHANGELOG.md
lib/js/tests/Webapi/Dom/Webapi__Dom__DomTokenList__test.js
src/Webapi/Dom/Webapi__Dom__DomTokenList.res
tests/Webapi/Dom/Webapi__Dom__DomTokenList__test.res

Fixes #134 
I took a quick look for other similar issues, but I didn't see any. Admittedly, I didn't look particularly carefully, though.

Allow toggleForced to force `false`

---

src/Webapi/Dom/Webapi__Dom__MediaQueryList.res
src/Webapi/Dom/Webapi__Dom__Window.res
src/Webapi/Webapi__Dom.res

https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList

Add 'Webapi.Dom.MediaQueryList'
